// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-PeJ5lTiIynhwpwt5tBZBVnqOeeRPXBU',
    appId: '1:950065881889:web:38aa24ead0f8114ed3d460',
    messagingSenderId: '950065881889',
    projectId: 'fir-project-29db1',
    authDomain: 'fir-project-29db1.firebaseapp.com',
    storageBucket: 'fir-project-29db1.firebasestorage.app',
    measurementId: 'G-C96VECPZFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEchjnXRBrS66UYtG6k_vTORuvsRFhAGE',
    appId: '1:950065881889:android:39331a8bf7e6601ad3d460',
    messagingSenderId: '950065881889',
    projectId: 'fir-project-29db1',
    storageBucket: 'fir-project-29db1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHcwySs8e-GdqoL8SfqdUkEZ5SLjsTRpk',
    appId: '1:950065881889:ios:18173c1079b5b679d3d460',
    messagingSenderId: '950065881889',
    projectId: 'fir-project-29db1',
    storageBucket: 'fir-project-29db1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHcwySs8e-GdqoL8SfqdUkEZ5SLjsTRpk',
    appId: '1:950065881889:ios:18173c1079b5b679d3d460',
    messagingSenderId: '950065881889',
    projectId: 'fir-project-29db1',
    storageBucket: 'fir-project-29db1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-PeJ5lTiIynhwpwt5tBZBVnqOeeRPXBU',
    appId: '1:950065881889:web:c912f301dee27c19d3d460',
    messagingSenderId: '950065881889',
    projectId: 'fir-project-29db1',
    authDomain: 'fir-project-29db1.firebaseapp.com',
    storageBucket: 'fir-project-29db1.firebasestorage.app',
    measurementId: 'G-679ZQ33W68',
  );
}
